language: ruby
dist: bionic
cache: bundler

rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.1
  - ruby-head
  - jruby

sudo: false

env:
  - ESCAPE_UTILS=1
  - ""

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: jruby
      env: ESCAPE_UTILS=1
